In [2]:
def ex():
    print("first sentence")
    print("error ", 15 + '15')
    print("last sentence")
    
ex()

first sentence


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [3]:
def ex2():
    print("first sentence")
    
    try:
        print("error ", 15 + '15')
    except TypeError :
        print("error message")
        
    print("last sentence")
    
ex2() 

first sentence
error message
last sentence


In [4]:
def ex3():
    print("first sentence")
    
    try:
        print("error ", 15 + '15') 
    except TypeError as te:
        print("error is {}".format(te))
        
    print("last sentence")
    
ex3()

first sentence
error is unsupported operand type(s) for +: 'int' and 'str'
last sentence


In [9]:
def ex4():
    print("first sentence")
    
    try:
        print("error ", 15 + '15') 
        
    except TypeError as te:
        print("error is {}".format(te))
        
    finally:
        print("real last sentence")
        
    print("last sentence")

    
ex4()

first sentence
error is unsupported operand type(s) for +: 'int' and 'str'
real last sentence
last sentence


In [10]:
import traceback

def ex5():
    print("first sentence")
    
    try:
        print("error ", 15 + '15') 
    except TypeError as te:
        print("error is below")
        traceback.print_exc()
        
    print("last sentence")
    
ex5()

first sentence
error is below
last sentence


Traceback (most recent call last):
  File "<ipython-input-10-9c9948f265b4>", line 7, in ex5
    print("error ", 15 + '15')
TypeError: unsupported operand type(s) for +: 'int' and 'str'


In [11]:
f = open('./data/hello.txt', 'r')
f.read()

'Hello, Jupyter !!'

In [12]:
f.close()

In [13]:
f.read()

ValueError: I/O operation on closed file.

In [26]:
f = open('./data/subject.txt', 'r')   # read
f.read()

'파이썬을 이용한 빅데이터 분석!!'

In [27]:
with open('./data/subject.txt', 'a') as f2:   # add contents
    data = 'Data Science with Python'
    f2.write(data)

In [28]:
f = open('./data/subject.txt', 'r')
f.read()

'파이썬을 이용한 빅데이터 분석!!Data Science with Python'

In [30]:
with open('./data/subject.txt', 'w') as f2:   # overwrite
    data = '파이썬을 이용한 빅데이터 분석!!'
    f2.write(data)
    
f = open('./data/subject.txt', 'r') 
f.read()

'파이썬을 이용한 빅데이터 분석!!'

In [45]:
def r_c(fpath):
    
    f = open(fpath, 'r', encoding = 'utf-8')
    data = f.read()
    f.close()
    
    elms = []
    
    rows = data.split('\n')
    
    for r in rows:
        
        fie = r.split(",")
        
        elm = {
            "name"   : fie[0],
            "school" : fie[1],
            "email"  : fie[2],       
               }
        elms.append(elm)
    return elms

In [46]:
fpath = './data/students.csv'
r_c(fpath)

[{'name': '김태희', 'school': '서울대', 'email': 'thkim@gmail.com'},
 {'name': '신민아', 'school': '성균관대', 'email': 'sma@gmial.com'},
 {'name': '전지현', 'school': '중앙대', 'email': 'jhjeon@gmail.com'},
 {'name': '이영애', 'school': '숭실대', 'email': 'janggumi@gamil.com'}]

In [50]:
def r_c(fpath):
    
    f = open(fpath, 'r', encoding = 'utf-8')
    data = f.read()
    f.close()
    
    elms = []
    
    rs = data.split('\n')
    cls = rs[0].split(',')  # columns names
    cls = [k.replace(' ', '') for k in cls]
    
    print(cls)
fpath = './data/company.csv'    
r_c(fpath)

['랭킹', '회사이름', '영문명', '창업자']


In [53]:
def r_c(fpath):
    
    f = open(fpath, 'r', encoding = 'utf-8')
    data = f.read()
    f.close()
    
    elms = []
    
    rs = data.split('\n')
    cls = rs[0].split(',')  # columns names
    cls = [k.replace(' ', '') for k in cls]
    
    for r in rs[1:]:
        fie = r.split(',')
        elm = {}
        
        if len(fie) != len(cls):
            continue
        for idx in range(len(cls)):   # index값 비교
            cl = cls[idx]
            fi = fie[idx]
            elm[cl] = fi
        elms.append(elm)
        
    return elms

In [54]:
fpath = './data/company.csv'    
r_c(fpath)

[{'랭킹': '1', '회사이름': ' 애플', '영문명': ' Apple', '창업자': ' 스티브잡스'},
 {'랭킹': '2', '회사이름': ' 구글', '영문명': ' Google', '창업자': ' 세르게이브린 & 레리페이지'},
 {'랭킹': '3', '회사이름': ' 마이크로소프트', '영문명': ' Microsoft', '창업자': ' 빌게이츠 & 폴앨런'},
 {'랭킹': '4', '회사이름': ' 페이스북', '영문명': ' Facebook', '창업자': ' 마크쥬크버그'},
 {'랭킹': '5', '회사이름': ' 에어비엔비', '영문명': ' Airbnb', '창업자': ' 브라이언체크키 & 조게비어'}]

In [55]:
from numpy.random import randn
import numpy as np

In [56]:
da = randn(2, 3)
da

array([[-1.19011076,  0.87156314,  0.32012756],
       [ 0.17045279, -0.64275473,  1.17913749]])

In [57]:
da * 10

array([[-11.90110759,   8.71563138,   3.20127564],
       [  1.70452786,  -6.42754734,  11.79137491]])

In [58]:
da + da

array([[-2.38022152,  1.74312628,  0.64025513],
       [ 0.34090557, -1.28550947,  2.35827498]])

In [60]:
da.shape

(2, 3)

In [61]:
da.dtype

dtype('float64')

In [62]:
da1 = [5, 6.8, 9, 0, 7]
ar1 = np.array(da1)
ar1

array([5. , 6.8, 9. , 0. , 7. ])

In [69]:
ar1.dtype

dtype('float64')

In [64]:
ar1.shape

(5,)

In [65]:
da2 = [[1, 2, 3, 4,], [9, 8, 7, 6]]
ar2 = np.array(da2)
ar2

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [66]:
ar2.ndim

2

In [67]:
ar2.shape

(2, 4)

In [68]:
ar2.dtype

dtype('int32')

In [70]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [78]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [77]:
a = np.empty((2, 3, 2))
a.shape

(2, 3, 2)

In [80]:
np.full((3, 3), 3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [81]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [82]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [83]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [84]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [86]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
ar1 = np.array([1, 2, 3], dtype = np.float64)
ar2 = np.array([1, 2, 3], dtype = np.int32)

print(ar1.dtype)
print(ar2.dtype)

float64
int32


In [88]:
ar3 = np.array([1.8, -2.3, 4.5, 6, 11.32])
print(ar3.dtype)
ar3

float64


array([ 1.8 , -2.3 ,  4.5 ,  6.  , 11.32])

In [89]:
ar3.astype(np.int32)

array([ 1, -2,  4,  6, 11])

In [90]:
ar4_str = np.array(['3.14', '6.25', '7.17', '50'], dtype = np.string_)
print(ar4_str.dtype)
ar4_str

|S4


array([b'3.14', b'6.25', b'7.17', b'50'], dtype='|S4')

In [91]:
ar4_str.astype(float)

array([ 3.14,  6.25,  7.17, 50.  ])

In [93]:
ar5 = np.arange(10)
ar5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
ar6 = np.array([.34, .55, .04, .004], dtype = np.float64)
ar6

array([0.34 , 0.55 , 0.04 , 0.004])

In [96]:
ar5.astype(ar6.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [97]:
# u4와  unit32는 동일

ar7 = np.empty(8, dtype = 'u4')
ar7

array([1546188227, 1070973583, 2576980378, 1071749529, 1202590843,
       1067743969, 3539053052, 1064329805], dtype=uint32)

In [99]:
ar8 =  np.array([[10., 12., 14.], [8., 9., 10.]])
ar8

array([[10., 12., 14.],
       [ 8.,  9., 10.]])

In [100]:
ar8 * ar8

array([[100., 144., 196.],
       [ 64.,  81., 100.]])

In [101]:
ar8 + ar8

array([[20., 24., 28.],
       [16., 18., 20.]])

In [102]:
ar8 - ar8

array([[0., 0., 0.],
       [0., 0., 0.]])

In [103]:
1/ ar8

array([[0.1       , 0.08333333, 0.07142857],
       [0.125     , 0.11111111, 0.1       ]])

In [104]:
ar8 ** 2

array([[100., 144., 196.],
       [ 64.,  81., 100.]])

In [105]:
ar5 = np.arange(10)
ar5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
ar5[0]

0

In [107]:
ar5[1]

1

In [108]:
ar5[-1]

9

In [109]:
ar5[5:9]

array([5, 6, 7, 8])

In [111]:
ar5[5:9] = 10
ar5

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10,  9])

In [112]:
ar5_s = ar5[5:9]
ar5_s

array([10, 10, 10, 10])

In [113]:
ar5_s[:] = 15
ar5

array([ 0,  1,  2,  3,  4, 15, 15, 15, 15,  9])