> 워드 클라우드 필요 패키지
    - konlpy (설치 필요)
    - pytagcloud - pygame (설치 필요)
    - collections.Counter (기본 설치)
    - wordcloud.WordCloud (설치 필요)
    - feedparser (설치 필요)

In [ ]:
# http://konlpy.org/ko/v0.4.3/examples/wordcloud/
# https://financedata.github.io/posts/python_news_cloud_text.html
# http://pinkwink.kr/1029
# https://thinkwarelab.wordpress.com/2016/08/30/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%ED%98%95%ED%83%9C%EC%86%8C-%EB%B6%84%EC%84%9D%EC%9C%BC%EB%A1%9C-%EC%9B%8C%EB%93%9C%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C-%EA%B7%B8%EB%A6%AC%EA%B8%B0/

#  
#  

In [6]:
import numpy as np

In [9]:
def read_csv(filepath):
    
    fp = open(filepath, 'r', encoding='utf-8')
    data = fp.read()
    fp.close()
    
    # return dataL
    elements = []
    
    rows = data.split("\n")
    
    print(rows)

In [10]:
filepath = 'data/students.csv'
read_csv(filepath)

['김태희,서울대,thkim@gmail.com', '신민아,성균관대,sma@gmial.com', '전지현,중앙대,jhjeon@gmail.com', '이영애,숭실대,janggumi@gamil.com']


#### jason

In [11]:
import json

j_d = { 
       'Class' : 'A', 
       'name' : 'Jane', 
       'Age' : 20, 
       'Country'  : 'Korean'
      }

In [12]:
j_c = json.JSONEncoder().encode(j_d)
j_c

'{"Class": "A", "name": "Jane", "Age": 20, "Country": "Korean"}'

In [13]:
print(j_c)

{"Class": "A", "name": "Jane", "Age": 20, "Country": "Korean"}


In [14]:
che = json.dumps('한글')
print(che)

"\ud55c\uae00"


In [16]:
che = json.dumps('한글', ensure_ascii = False)
print(che)

"한글"


In [18]:
che = json.dumps(j_d, ensure_ascii = False)
print(che)

{"Class": "A", "name": "Jane", "Age": 20, "Country": "Korean"}


In [19]:
j_c = json.JSONDecoder().decode(che)
j_c

{'Class': 'A', 'name': 'Jane', 'Age': 20, 'Country': 'Korean'}

In [21]:
j_c['Country']

'Korean'

In [22]:
class Person:
    name = str()
    age  = int()
    hometown = str()
    
    def __init__(self, name, age, hometown):
        self.name = name
        self.age  = age
        self.hometown = hometown
        
    def to_string(self):
        # str = '나의 살던 고향은 ' + self.hometown + '입니다.'
        str = '%s의 나이는 %d살이고, 고향은 %s입니다.' % (self.name, self.age, self.hometown)
        return str        
        
    

In [27]:
thf1 = Person("장원영", 16, "서울")
thf2 = Person("히토미", 18, "토치키현")

In [29]:
thf1

In [30]:
thf1.to_string()

'장원영의 나이는 16살이고, 고향은 서울입니다.'

In [31]:
thf2.to_string()

'히토미의 나이는 18살이고, 고향은 토치키현입니다.'

In [125]:
data = '''
    {
        "name" : "홍길동",
        "dog"  : {
            "name" : "순둥이",
            "toys" : [
                    { "name" : "뽀로로" },
                    { "name" : "토마스" }
            ]
        }
    }
'''

In [126]:
with open('data/person.json', 'w') as fp:
    fp.write(data)

In [127]:
with open('data/person.json') as data_file:    
    person = json.load(data_file)
    
print(person)

{'name': '홍길동', 'dog': {'name': '순둥이', 'toys': [{'name': '뽀로로'}, {'name': '토마스'}]}}


In [135]:
"{}의 개 {}의 장난감은 {}, {}입니다.".format(
        person["name"],
        person["dog"]["name"],
        person["dog"]["toys"][0]["name"],
        person["dog"]["toys"][1]["name"]  
)

'홍길동의 개 순둥이의 장난감은 뽀로로, 토마스입니다.'

####    

In [ ]:
# http://sinpong.tistory.com/120
# 넘파이

In [33]:
ar10 = np.arange(12).reshape(3,4)
ar10

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
ar10.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [36]:
ar10T = ar10.T
ar10T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [37]:
ardot = np.dot(ar10, ar10T)
ardot

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [47]:
artp = np.transpose(ar10)
artp

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [55]:
arfl = ar10.flatten()
arfl

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
arrv = ar10.ravel()
arrv

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [59]:
arr.transpose((1, 0, 2 ))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [60]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [61]:
ar2 = np.arange(9).reshape(3, 3)
ar2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
ar2[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
ar2[0]

array([0, 1, 2])

In [64]:
ar2[-1]

array([6, 7, 8])

In [65]:
ar2[:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
ar2[:1, :]

array([[0, 1, 2]])

In [69]:
ar2[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [70]:
ar2[:1]

array([[0, 1, 2]])

In [71]:
ar2[:, :1]

array([[0],
       [3],
       [6]])

In [72]:
ar2[2, :1]

array([6])

In [74]:
ar2[1:, 2:] = 0
ar2

array([[0, 1, 2],
       [3, 4, 0],
       [6, 7, 0]])

In [75]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [80]:
from numpy.random import randn

data = randn(7, 4)
data

array([[ 0.47579342, -0.89390999, -1.92070486, -0.34297564],
       [ 1.55912952,  1.38828125, -0.51090524, -1.1550864 ],
       [-0.0338252 ,  0.21978604,  0.21064315, -0.86896211],
       [-2.09473351,  0.73979139, -0.20769595,  0.29009243],
       [-0.17575179, -0.14607182,  1.88865035, -0.77657928],
       [ 1.7167252 , -1.2122332 ,  0.24550268, -0.90732217],
       [ 1.01380121, -0.58937972, -1.10911753, -1.04445646]])

In [81]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [82]:
data[names == 'Bob']

array([[ 0.47579342, -0.89390999, -1.92070486, -0.34297564],
       [-2.09473351,  0.73979139, -0.20769595,  0.29009243]])

In [84]:
data[names != 'Bob']

array([[ 1.55912952,  1.38828125, -0.51090524, -1.1550864 ],
       [-0.0338252 ,  0.21978604,  0.21064315, -0.86896211],
       [-0.17575179, -0.14607182,  1.88865035, -0.77657928],
       [ 1.7167252 , -1.2122332 ,  0.24550268, -0.90732217],
       [ 1.01380121, -0.58937972, -1.10911753, -1.04445646]])

In [85]:
data[names == 'Bob', 2:]

array([[-1.92070486, -0.34297564],
       [-0.20769595,  0.29009243]])

In [88]:
data[-(names == 'Bob')]

TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

In [89]:
data[~(names == 'Bob')]

array([[ 1.55912952,  1.38828125, -0.51090524, -1.1550864 ],
       [-0.0338252 ,  0.21978604,  0.21064315, -0.86896211],
       [-0.17575179, -0.14607182,  1.88865035, -0.77657928],
       [ 1.7167252 , -1.2122332 ,  0.24550268, -0.90732217],
       [ 1.01380121, -0.58937972, -1.10911753, -1.04445646]])

In [90]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [91]:
data[mask]

array([[ 0.47579342, -0.89390999, -1.92070486, -0.34297564],
       [-0.0338252 ,  0.21978604,  0.21064315, -0.86896211],
       [-2.09473351,  0.73979139, -0.20769595,  0.29009243],
       [-0.17575179, -0.14607182,  1.88865035, -0.77657928]])

In [92]:
data[data < 0] = 0
data

array([[0.47579342, 0.        , 0.        , 0.        ],
       [1.55912952, 1.38828125, 0.        , 0.        ],
       [0.        , 0.21978604, 0.21064315, 0.        ],
       [0.        , 0.73979139, 0.        , 0.29009243],
       [0.        , 0.        , 1.88865035, 0.        ],
       [1.7167252 , 0.        , 0.24550268, 0.        ],
       [1.01380121, 0.        , 0.        , 0.        ]])

In [93]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.55912952, 1.38828125, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.7167252 , 0.        , 0.24550268, 0.        ],
       [1.01380121, 0.        , 0.        , 0.        ]])

In [94]:
ar11 = np.arange(9).reshape((3, 3))
ar11

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
np.diag(ar11)

array([0, 4, 8])

In [96]:
np.diag(ar11, 1)

array([1, 5])

In [97]:
np.diag(ar11, k = 1)

array([1, 5])

In [98]:
np.diag(ar11, k = -1)

array([3, 7])

In [99]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [100]:
arr[[1, 3, 5, 7]]

array([[1., 1., 1., 1.],
       [3., 3., 3., 3.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.]])

In [101]:
arr[[-6, -2, -4]]

array([[2., 2., 2., 2.],
       [6., 6., 6., 6.],
       [4., 4., 4., 4.]])

In [102]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [103]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [104]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [106]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [113]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [105]:
arr[[0, 1, 6, 4], [0, 1, 2, 1]]

array([ 0,  5, 26, 17])

In [112]:
arr[[0, 1, 6, 4]][:, [0, 1, 2, 1]]

array([[ 0,  1,  2,  1],
       [ 4,  5,  6,  5],
       [24, 25, 26, 25],
       [16, 17, 18, 17]])

In [114]:
arr[np.ix_([0, 1, 6, 4], [0, 1, 2, 1])]

array([[ 0,  1,  2,  1],
       [ 4,  5,  6,  5],
       [24, 25, 26, 25],
       [16, 17, 18, 17]])

In [115]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [118]:
arr[[3, 4, 5],[1, 2, 3]]

array([13, 18, 23])

In [119]:
arr[np.ix_([3, 4, 5],[1, 2, 3])]

array([[13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [121]:
arr[[3, 4, 5]][:,[1,2,3]]

array([[13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [122]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [123]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
arr.transpose((1, 0, 2))  # axis 0, 1, 2
# axis 1이 었던게 0으로 가고 axis 0이었던게 1로 간다.
# [4, 5, 6, 7] <-> [8, 9, 10, 11]

In [124]:
arr.swapaxes(1, 2)

# aixs 1과 axis 2를 축을 기준을 바꿈 
# 위에 결과를 왼쪽에서부터 보면 된다.
[0, 1, 2, 3,]
[4, 5, 6, 7]
이 [0, 4], [1, 5], [2, 6], [3, 7]

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])