In [1]:
import tensorflow as tf

import numpy as np
import matplotlib.pyplot as plt

tf.__version__

C:\Users\Jeong\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


'1.10.0'

In [3]:
hello = tf.constant("Hello! TensorFlow")

sess = tf.Session()
hello

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [4]:
sess.run(hello)

b'Hello! TensorFlow'

In [5]:
result = sess.run(hello)
type(result)

bytes

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
type(sess)

tensorflow.python.client.session.Session

#### Graph

In [10]:
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0)

node3 = tf.add(node1, node2)
node4 = node1 + node2

In [11]:
print("node1 :", node1)
print("node2 :", node2)
print("node3 :", node3)
print("node4 :", node4)

node1 : Tensor("Const_4:0", shape=(), dtype=float32)
node2 : Tensor("Const_5:0", shape=(), dtype=float32)
node3 : Tensor("Add_1:0", shape=(), dtype=float32)
node4 : Tensor("add_2:0", shape=(), dtype=float32)


In [13]:
sess = tf.Session()

print("sess.run(node1, node2)\t: ", sess.run([node1, node2]))
print("sess.run(adder_node)  \t: ", sess.run(node3))

sess.run(node1, node2)	:  [3.0, 4.0]
sess.run(adder_node)  	:  7.0


In [14]:
type(node3)

tensorflow.python.framework.ops.Tensor

In [15]:
type(node4)

tensorflow.python.framework.ops.Tensor

In [16]:
type(sess.run(node3))

numpy.float32

#### TF Mechanics

##### placeholder

In [18]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

adder_node = a + b

In [19]:
sess.run(adder_node, feed_dict = {a : 5, b : 7})

12.0

In [20]:
sess.run(adder_node, feed_dict = {a : [1, 5], b : [2, 7]})

array([ 3., 12.], dtype=float32)

In [21]:
add_triple = adder_node * 3.

In [22]:
sess.run(add_triple, feed_dict = {a : 2, b : 3.5})

16.5

In [25]:
a = tf.placeholder("int32")
b = tf.placeholder("int32")

y = tf.add(a, b)

sess = tf.Session()

print("tf.add({a}, {b}) : {y}".format( 
      a = 10, b = 20,
      y = sess.run(y, feed_dict = {a : 10, b : 20})
))

tf.add(10, 20) : 30


In [26]:
a = tf.placeholder("int32")
b = tf.placeholder("int32")

y = tf.multiply(a, b)

sess = tf.Session()

a_var = 20.
b_var = 40.

print("tf.multiply({a}, {b}) : {y}".format( 
      a = a_var, b = b_var,
      y = sess.run(y, feed_dict = {a : a_var, b : b_var})
))

tf.multiply(20.0, 40.0) : 800


##### constant & variable

In [30]:
x = tf.constant(100, name = 'x')
y = tf.Variable(x*2, name = 'y')

model = tf.global_variables_initializer()
# model = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(model)
    print("Check the variable : \n - constant x : {x} \n - Variable y : {y}".format(
           x = sess.run(x),
           y = sess.run(y)
))

Check the variable : 
 - constant x : 100 
 - Variable y : 200


##### shape, dimension

In [31]:
rank0 = 3
rank0 = np.array(rank0)
rank0, rank0.shape

(array(3), ())

In [32]:
rank1 = [1. ,2., 3.]
rank1 = np.array(rank1)
rank1, rank1.shape

(array([1., 2., 3.]), (3,))

In [33]:
rank2 = [[1., 2., 3.], 
         [4., 5., 6.]]
rank2 = np.array(rank2)
rank2, rank2.shape

(array([[1., 2., 3.],
        [4., 5., 6.]]), (2, 3))

In [34]:
rank3 = [
            [
                [1., 2., 3.]
            ], 
            [
                [7., 8., 9.]
            ]
] 
rank3 = np.array(rank3)
rank3, rank3.shape

(array([[[1., 2., 3.]],
 
        [[7., 8., 9.]]]), (2, 1, 3))

#### TensorFlow Calculation

In [35]:
tens1 = np.array([1.2, 3.4, 5.6, 7.8])
tens1

array([1.2, 3.4, 5.6, 7.8])

In [36]:
tens2 = np.arange(16).reshape((4,4))
tens2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
sess = tf.Session()

tf_tens1 = tf.convert_to_tensor(tens1, dtype = tf.float64)
tf_tens2 = tf.convert_to_tensor(tens2, dtype = tf.float64)

In [39]:
tf_tens1

<tf.Tensor 'Const_6:0' shape=(4,) dtype=float64>

In [40]:
sess.run(tf_tens1)

array([1.2, 3.4, 5.6, 7.8])

In [41]:
sess.run(tf_tens1[0])

1.2

In [42]:
sess.run(tf_tens1[1:])

array([3.4, 5.6, 7.8])

In [43]:
tf_tens2

<tf.Tensor 'Const_7:0' shape=(4, 4) dtype=float64>

In [44]:
sess.run(tf_tens2)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [45]:
sess.run(tf_tens2[-1])

array([12., 13., 14., 15.])

In [46]:
sess.run(tf_tens2[3, 3])

15.0

In [47]:
sess.run(tf_tens2[1, 1])

5.0

#### TensorFlow Matrix Calculation

In [49]:
matrix1 = np.array([(1, 1, 1), (1, 1, 1), (1, 1, 1)])
matrix2 = np.array([(2, 2, 2), (2, 2, 2), (2, 2, 2)])

print(matrix1)
print(" ")
print(matrix2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
 
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [50]:
matrix1 = tf.constant(matrix1, dtype='int32')
matrix2 = tf.constant(matrix2, dtype='int32')

In [54]:
matrix_mul = tf.matmul(matrix1, matrix2)
matrix_add = tf.add(matrix1, matrix2)

matrix3 = np.array([(2, 7, 2), (1, 4, 2), (9, 0, 2)], dtype='float32')
matrix_dtm = tf.matrix_determinant(matrix3)  

print('\nmatrix3 = \n{}'.format(matrix3))
print('\nmatrix_dtm = {}\n'.format(matrix_dtm))

# tf.matrix_determinant 정방행렬의 행렬식 값을 리턴


matrix3 = 
[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]

matrix_dtm = Tensor("MatrixDeterminant_1:0", shape=(), dtype=float32)



In [55]:
with tf.Session() as sess:
    result1 = sess.run(matrix_mul)
    result2 = sess.run(matrix_add)
    result3 = sess.run(matrix_dtm)
    
print('\nmatrix_mul = \n{}'.format(result1))
print('\nmatrix_sum = \n{}'.format(result2))
print('\nmatrix_dtm = {}\n'.format(result3))


matrix_mul = 
[[6 6 6]
 [6 6 6]
 [6 6 6]]

matrix_sum = 
[[3 3 3]
 [3 3 3]
 [3 3 3]]

matrix_dtm = 55.99999237060547



In [ ]:
# tensorboard for graph
# writer = tf.summary.FileWriter("./graph/sect01", sess.graph)