In [6]:
from tqdm import tqdm_notebook
import tensorflow as tf

In [ ]:
quiz1(x1)  quiz2(x2)  midterm1(x3)  final(Y)    
   73         80          75           152
   93         88          93           185
   89         91          90           180
   96         98         100           198
   73         66          70           142

#### multi-variable linear regression

In [2]:
import tensorflow as tf

tf.set_random_seed(777) # 재현을 위해

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]


x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b  = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1 * w1 + x2 * w3 + x3 * w3 + b
print(hypothesis)

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

Tensor("add_2:0", dtype=float32)


In [3]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2001)):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict = {x1 : x1_data, x2 : x2_data, x3 : x3_data, Y : y_data})
    
    if step % 100 == 0 or step < 10:
        print("\nStep : {} \nCost : {} \nPrediction : \n{}".format(step, cost_val, hy_val))


Step : 0 
Cost : 25309.24609375 
Prediction : 
[ 9.406108 15.630229 13.277722 13.773341 13.453403]

Step : 1 
Cost : 1783.132080078125 
Prediction : 
[113.85797  139.70802  136.26949  147.94751  107.531425]

Step : 2 
Cost : 125.85054016113281 
Prediction : 
[141.58087 172.63995 168.91315 183.55911 132.50107]

Step : 3 
Cost : 9.104373931884766 
Prediction : 
[148.93886 181.38057 177.57721 193.01088 139.12837]

Step : 4 
Cost : 0.8801765441894531 
Prediction : 
[150.89174 183.70049 179.87675 195.5195  140.88742]

Step : 5 
Cost : 0.30080538988113403 
Prediction : 
[151.41003 184.31625 180.48709 196.18532 141.35435]

Step : 6 
Cost : 0.2599765360355377 
Prediction : 
[151.54753 184.4797  180.64905 196.36198 141.47832]

Step : 7 
Cost : 0.2570776045322418 
Prediction : 
[151.58401 184.52315 180.69205 196.40889 141.51129]

Step : 8 
Cost : 0.2568546235561371 
Prediction : 
[151.59364 184.53467 180.70343 196.42128 141.52008]

Step : 9 
Cost : 0.2568219304084778 
Prediction : 
[151.59616 1

In [4]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2001)):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})

    if step % 100 == 0 or step < 10 :
        print("\nStep : {} \nCost : {} \nPrediction :\n{}".format(step, cost_val, hy_val))



Step : 0 
Cost : 25309.24609375 
Prediction :
[ 9.406108 15.630229 13.277722 13.773341 13.453403]

Step : 1 
Cost : 1783.132080078125 
Prediction :
[113.85797  139.70802  136.26949  147.94751  107.531425]

Step : 2 
Cost : 125.85054016113281 
Prediction :
[141.58087 172.63995 168.91315 183.55911 132.50107]

Step : 3 
Cost : 9.104373931884766 
Prediction :
[148.93886 181.38057 177.57721 193.01088 139.12837]

Step : 4 
Cost : 0.8801765441894531 
Prediction :
[150.89174 183.70049 179.87675 195.5195  140.88742]

Step : 5 
Cost : 0.30080538988113403 
Prediction :
[151.41003 184.31625 180.48709 196.18532 141.35435]

Step : 6 
Cost : 0.2599765360355377 
Prediction :
[151.54753 184.4797  180.64905 196.36198 141.47832]

Step : 7 
Cost : 0.2570776045322418 
Prediction :
[151.58401 184.52315 180.69205 196.40889 141.51129]

Step : 8 
Cost : 0.2568546235561371 
Prediction :
[151.59364 184.53467 180.70343 196.42128 141.52008]

Step : 9 
Cost : 0.2568219304084778 
Prediction :
[151.59616 184.53777 1

#### multi-variable matmul linear regression

In [5]:
import tensorflow as tf
tf.set_random_seed(777) 

x_data = [[73., 80., 75.], 
          [93., 88., 93.],
          [89., 91., 90.], 
          [96., 98., 100.], 
          [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]),    name = 'bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [7]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2001)):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict = {X : x_data, Y : y_data})
    
    if step % 100 == 0 or step < 10:
        print("\nStep : {} \nCost : {} \nPrediction : \n{}".format(step, cost_val, hy_val))


Step : 0 
Cost : 56385.375 
Prediction : 
[[-58.458176]
 [-68.91279 ]
 [-68.36896 ]
 [-77.1176  ]
 [-50.047306]]

Step : 1 
Cost : 17674.509765625 
Prediction : 
[[34.27563 ]
 [42.5463  ]
 [41.4536  ]
 [42.476444]
 [34.96787 ]]

Step : 2 
Cost : 5540.7080078125 
Prediction : 
[[ 86.193886]
 [104.94814 ]
 [102.939224]
 [109.43279 ]
 [ 82.56472 ]]

Step : 3 
Cost : 1737.4066162109375 
Prediction : 
[[115.261024]
 [139.88464 ]
 [137.36275 ]
 [146.9192  ]
 [109.21242 ]]

Step : 4 
Cost : 545.2735595703125 
Prediction : 
[[131.53464 ]
 [159.4443  ]
 [156.63521 ]
 [167.90648 ]
 [124.131485]]

Step : 5 
Cost : 171.60275268554688 
Prediction : 
[[140.64566]
 [170.39505]
 [167.42519]
 [179.65651]
 [132.48409]]

Step : 6 
Cost : 54.4771728515625 
Prediction : 
[[145.74657]
 [176.52594]
 [173.46606]
 [186.23494]
 [137.16037]]

Step : 7 
Cost : 17.764415740966797 
Prediction : 
[[148.60239]
 [179.9584 ]
 [176.84814]
 [189.91797]
 [139.77844]]

Step : 8 
Cost : 6.256844997406006 
Prediction : 
[[1

#### file input linear regression

In [9]:
import numpy as np

xy = np.loadtxt('./data/data-01-test-score.csv', delimiter=',', dtype=np.float32)
xy

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

In [11]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print("# Check the train data")
print("-"*50)
print("x_data.shape : {},   len(x_data) : {} \nx_data : \n{}".format(x_data.shape, len(x_data), x_data))
print("-"*50)
print("y_data.shape : {},   len(y_data) : {} \ny_data : \n{}".format(y_data.shape, len(y_data), y_data))

# Check the train data
--------------------------------------------------
x_data.shape : (25, 3),   len(x_data) : 25 
x_data : 
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
--------------------------------------------------
y_data.shape : (25, 1),   len(y_data) : 25 
y_data : 
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [12]:
import tensorflow as tf
tf.set_random_seed(777)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [13]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2001)):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict = {X : x_data, Y : y_data})
    
    if step % 100 == 0 or step < 10:
        print("\nStep : {} \nCost : {} \nPrediction : \n{}".format(step, cost_val, hy_val))


Step : 0 
Cost : 37653.984375 
Prediction : 
[[-25.132015]
 [-35.24543 ]
 [-31.989025]
 [-36.701427]
 [-26.571817]
 [-23.006609]
 [-28.792574]
 [-23.052807]
 [-36.35996 ]
 [-38.214752]
 [-27.328386]
 [-29.869019]
 [-31.243298]
 [-23.6406  ]
 [-29.879856]
 [-37.070248]
 [-21.815804]
 [-34.584045]
 [-28.713585]
 [-25.473568]
 [-33.8438  ]
 [-34.546   ]
 [-31.308651]
 [-21.10814 ]
 [-34.87119 ]]

Step : 1 
Cost : 13947.6103515625 
Prediction : 
[[46.33806 ]
 [50.65833 ]
 [52.651524]
 [55.4798  ]
 [38.943596]
 [25.29753 ]
 [40.209206]
 [28.102087]
 [43.925495]
 [36.15214 ]
 [39.150978]
 [35.682976]
 [56.200893]
 [49.049583]
 [39.439728]
 [50.10273 ]
 [47.411575]
 [48.224842]
 [54.651234]
 [49.117943]
 [47.071774]
 [46.044235]
 [45.83734 ]
 [50.947933]
 [54.157017]]

Step : 2 
Cost : 5182.68701171875 
Prediction : 
[[ 89.79476 ]
 [102.89255 ]
 [104.116974]
 [111.53083 ]
 [ 78.780464]
 [ 54.669968]
 [ 82.16633 ]
 [ 59.20781 ]
 [ 92.7444  ]
 [ 81.37341 ]
 [ 79.57418 ]
 [ 75.54303 ]
 [109.370

 [191.81238 ]]

Step : 1200 
Cost : 18.741043090820312 
Prediction : 
[[155.24876 ]
 [184.44604 ]
 [182.88571 ]
 [198.54884 ]
 [140.67767 ]
 [102.543495]
 [148.32672 ]
 [109.60189 ]
 [171.13728 ]
 [156.96742 ]
 [142.90967 ]
 [139.73842 ]
 [189.53732 ]
 [158.31966 ]
 [148.62204 ]
 [186.77553 ]
 [150.87401 ]
 [178.08708 ]
 [181.12755 ]
 [162.19568 ]
 [173.83202 ]
 [172.57524 ]
 [166.0966  ]
 [157.9213  ]
 [191.77756 ]]

Step : 1300 
Cost : 17.72362518310547 
Prediction : 
[[155.1303 ]
 [184.47452]
 [182.81938]
 [198.55394]
 [140.67802]
 [102.68303]
 [148.3976 ]
 [109.74316]
 [171.298  ]
 [157.30252]
 [142.94946]
 [139.8827 ]
 [189.39256]
 [158.10014]
 [148.72733]
 [186.86235]
 [150.62404]
 [178.18144]
 [180.95093]
 [162.0332 ]
 [173.91216]
 [172.66653]
 [166.13646]
 [157.62386]
 [191.74377]]

Step : 1400 
Cost : 16.790021896362305 
Prediction : 
[[155.01743 ]
 [184.50114 ]
 [182.75592 ]
 [198.55896 ]
 [140.67749 ]
 [102.815994]
 [148.46606 ]
 [109.879585]
 [171.45114 ]
 [157.62277 ]
 [14

In [14]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2001)):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict = {X : x_data, Y : y_data})
    
    if step % 100 == 0 or step < 10:
        print("Step : {} \tCost : {} ".format(step, cost_val))

Step : 0 	Cost : 37653.984375 
Step : 1 	Cost : 13947.6103515625 
Step : 2 	Cost : 5182.68701171875 
Step : 3 	Cost : 1942.03369140625 
Step : 4 	Cost : 743.8551635742188 
Step : 5 	Cost : 300.8373107910156 
Step : 6 	Cost : 137.0222625732422 
Step : 7 	Cost : 76.43635559082031 
Step : 8 	Cost : 54.017330169677734 
Step : 9 	Cost : 45.70964050292969 
Step : 100 	Cost : 38.247440338134766 
Step : 200 	Cost : 35.61164855957031 
Step : 300 	Cost : 33.19538497924805 
Step : 400 	Cost : 30.980134963989258 
Step : 500 	Cost : 28.949073791503906 
Step : 600 	Cost : 27.086713790893555 
Step : 700 	Cost : 25.378890991210938 
Step : 800 	Cost : 23.812685012817383 
Step : 900 	Cost : 22.3762264251709 
Step : 1000 	Cost : 21.058618545532227 
Step : 1100 	Cost : 19.84992027282715 
Step : 1200 	Cost : 18.741043090820312 
Step : 1300 	Cost : 17.72362518310547 
Step : 1400 	Cost : 16.790021896362305 
Step : 1500 	Cost : 15.93323040008545 
Step : 1600 	Cost : 15.146841049194336 
Step : 1700 	Cost : 14.

#### predict score 

In [15]:
print("Your score \t: \n", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

Your score 	: 
 [[180.76924]]


In [16]:
print("\nOther scores \t: \n", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


Other scores 	: 
 [[162.21465]
 [183.13728]]


#### Tensorflow reader 

In [3]:
import tensorflow as tf

tf.set_random_seed(777)

filename_queue = tf.train.string_input_producer(
                 ['./data/data-01-test-score.csv'], shuffle = False, name = 'filename_queue')
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

print("# Check data")
print("-"*50)
print(train_x_batch)
print("-"*50)
print(train_y_batch)


# Check data
--------------------------------------------------
Tensor("batch:0", shape=(10, 3), dtype=float32)
--------------------------------------------------
Tensor("batch:1", shape=(10, 1), dtype=float32)


In [4]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [7]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()  # 쓰레드 컨트롤
threads = tf.train.start_queue_runners(sess = sess, coord = coord)

for step in tqdm_notebook(range(2001)):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
                          [cost, hypothesis, train], feed_dict = {X : x_batch, Y : y_batch})
    if step % 100 == 0 or step < 10:
        print("\nStep : {} \nCost : {} \nPrediction :\n{}".format(step, cost_val, hy_val))

coord.request_stop()
coord.join(threads)


Step : 0 
Cost : 150746.46875 
Prediction :
[[526.83954]
 [635.4824 ]
 [624.72455]
 [683.38306]
 [482.76044]
 [360.8742 ]
 [515.4113 ]
 [387.43497]
 [598.1317 ]
 [560.9038 ]]

Step : 1 
Cost : 63619.98828125 
Prediction :
[[365.33612]
 [362.32755]
 [473.0038 ]
 [389.09045]
 [384.1147 ]
 [478.5761 ]
 [367.6042 ]
 [459.4538 ]
 [450.13898]
 [403.08676]]

Step : 2 
Cost : 25774.12890625 
Prediction :
[[341.24332]
 [337.61478]
 [324.30878]
 [290.4762 ]
 [368.11182]
 [295.115  ]
 [356.89606]
 [350.26886]
 [384.46295]
 [270.2884 ]]

Step : 3 
Cost : 6661.2373046875 
Prediction :
[[161.94666]
 [231.2947 ]
 [176.81024]
 [267.51257]
 [254.63928]
 [220.41837]
 [219.47598]
 [282.31863]
 [230.54694]
 [233.02338]]

Step : 4 
Cost : 3331.156982421875 
Prediction :
[[255.10268]
 [190.06378]
 [247.15703]
 [236.36147]
 [211.8047 ]
 [239.40222]
 [236.17914]
 [227.21346]
 [199.79512]
 [256.05914]]

Step : 5 
Cost : 1170.9423828125 
Prediction :
[[182.83124]
 [221.94305]
 [217.29659]
 [239.64595]
 [167.36

#### predcit score

In [8]:
print("Your score \t: \n", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("\nOther scores \t: \n", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score 	: 
 [[187.20932]]

Other scores 	: 
 [[194.0139 ]
 [171.56538]]
