## Softmax Regression

In [2]:
from tqdm import tqdm_notebook
import tensorflow as tf

In [ ]:
hours(x1)     attendance(x2)     grade(y)
   10              5                A
    9              5                A
    3              2                B
    2              4                B
   11              1                C

In [ ]:
A = [1, 0, 0]
B = [0, 1, 0]
C = [0, 0, 1]

In [4]:
import tensorflow as tf
tf.set_random_seed(777)

x_data = [[10,5], [9,5], [3,2], [2,4], [11,1]]
y_data = [[1, 0, 0], 
          [1, 0, 0], 
          [0, 1, 0], 
          [0, 1, 0],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 2])
Y = tf.placeholder("float", [None, 3])
nb_class = 3

W = tf.Variable(tf.random_normal([2, nb_class]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_class]), name = 'bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

In [5]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2001)):
    sess.run(optimizer, feed_dict = { X : x_data, Y : y_data})
    
    if step % 200 == 0:
        print("Step : {}, \t Cost : {}".format(step, sess.run(cost, feed_dict = { X : x_data, Y : y_data})))

Step : 0, 	 Cost : 4.843900203704834
Step : 200, 	 Cost : 0.06746585667133331
Step : 400, 	 Cost : 0.04033724591135979
Step : 600, 	 Cost : 0.02914329245686531
Step : 800, 	 Cost : 0.022887172177433968
Step : 1000, 	 Cost : 0.018865345045924187
Step : 1200, 	 Cost : 0.01605486311018467
Step : 1400, 	 Cost : 0.013977574184536934
Step : 1600, 	 Cost : 0.01237854640930891
Step : 1800, 	 Cost : 0.011109257116913795
Step : 2000, 	 Cost : 0.010076854377985



In [6]:
scr = sess.run(hypothesis, feed_dict={X: [[9.5,5.5], [9.9, 1.5], [3.1, 2.1]]})
print(scr)
print(sess.run(tf.arg_max(scr, 1)))

[[9.9252325e-01 7.3787891e-03 9.7978191e-05]
 [2.2787986e-02 5.7418970e-07 9.7721148e-01]
 [3.1971574e-02 9.6467042e-01 3.3580705e-03]]
Instructions for updating:
Use `argmax` instead
[0 2 1]


* [9.9252325e-01 , 7.3787891e-03 , 9.7978191e-05] 중 가장 큰수는  '9.9252325e-01' 따라서 인덱스 0을 가져온다.
* [2.2787986e-02 , 5.7418970e-07 , 9.7721148e-01] 중 가장 큰수는  '9.7721148e-01' 따라서 인덱스 2를 가져온다.
* [3.1971574e-02 , 9.6467042e-01 , 3.3580705e-03] 중 가장 큰수는  '9.6467042e-01' 따라서 인덱스 1를 가져온다.

In [7]:
grade = ['A', 'B', 'C']
arg_val = sess.run(tf.arg_max(scr, 1))
p_grade = [grade[val] for val in arg_val]
print(p_grade)

['A', 'C', 'B']


#### more complex classification

In [3]:
import tensorflow as tf
tf.set_random_seed(777)

x_data = [[1, 2, 1, 1], 
          [2, 1, 3, 2], 
          [3, 1, 3, 4], 
          [4, 1, 5, 5],
          [1, 7, 5, 5], 
          [1, 2, 5, 6], 
          [1, 6, 6, 6], 
          [1, 7, 7, 7]]

y_data = [[0, 0, 1], 
          [0, 0, 1], 
          [0, 0, 1], 
          [0, 1, 0],
          [0, 1, 0], 
          [0, 1, 0], 
          [1, 0, 0], 
          [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_class = 3

W = tf.Variable(tf.random_normal([4, nb_class]), name = 'wieght')
b = tf.Variable(tf.random_normal([nb_class]), name = 'bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

In [10]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
    
for step in tqdm_notebook(range(2001)):
    sess.run(optimizer, feed_dict = {X : x_data, Y : y_data})
    if step % 200 == 0:
        print("Step : {}, \t Cost : {}".format(step, sess.run(cost, feed_dict={X: x_data, Y: y_data})))


Step : 0, 	 Cost : 5.048624515533447
Step : 200, 	 Cost : 0.5484252572059631
Step : 400, 	 Cost : 0.4321485459804535
Step : 600, 	 Cost : 0.35246652364730835
Step : 800, 	 Cost : 0.27682942152023315
Step : 1000, 	 Cost : 0.23268289864063263
Step : 1200, 	 Cost : 0.2105531543493271
Step : 1400, 	 Cost : 0.19221502542495728
Step : 1600, 	 Cost : 0.17675194144248962
Step : 1800, 	 Cost : 0.16353417932987213
Step : 2000, 	 Cost : 0.15210826694965363



In [12]:
scr1 = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
print(scr1, sess.run(tf.arg_max(scr1, 1)))

[[1.3890549e-03 9.9860185e-01 9.0613257e-06]] [1]


In [13]:
scr2 = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
print(scr2, sess.run(tf.arg_max(scr2, 1)))

[[0.9311918  0.06290228 0.00590593]] [0]


In [14]:
scr3 = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
print(scr3, sess.run(tf.arg_max(scr3, 1)))

[[1.2732816e-08 3.3411323e-04 9.9966586e-01]] [2]


In [15]:
all = sess.run(hypothesis, feed_dict={
               X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
print(all, sess.run(tf.arg_max(all, 1)))

[[1.3890548e-03 9.9860185e-01 9.0613094e-06]
 [9.3119180e-01 6.2902324e-02 5.9059337e-03]
 [1.2732816e-08 3.3411323e-04 9.9966586e-01]] [1 0 2]


#### Animal classification

In [ ]:
#   hair     Boolean"
#   feathers     Boolean"
#   eggs     Boolean"
#   milk     Boolean"
#   airborne     Boolean"
#   aquatic      Boolean"
#   predator     Boolean"
#   toothed      Boolean"
#   backbone     Boolean"
#   breathes     Boolean"
#   venomous     Boolean"
#   fins     Boolean"
#   legs     Numeric (set of values: {0, 2, 4, 5, 6, 8})
#   tail     Boolean"
#   domestic     Boolean"
#   catsize      Boolean"

# Birds, Insect Fishes, Amphibians, Reptiles, Mammals...

# frog,0,0,1,0,0,1,1,1,1,1,0,0,4,0,0,0,5
# leopard,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
# sparrow,0,1,1,0,1,0,0,0,1,1,0,0,2,1,0,0,2
# ...


In [17]:
import numpy as np

xy = np.loadtxt('./data/data-04-zoo.csv', delimiter = ',', dtype = np.float32)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)
print('x_data :\n', x_data)
print('y_data :\n', y_data)


(101, 16) (101, 1)
x_data :
 [[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 0. 0.]]
y_data :
 [[0.]
 [0.]
 [3.]
 [0.]
 [0.]
 [0.]
 [0.]
 [3.]
 [3.]
 [0.]
 [0.]
 [1.]
 [3.]
 [6.]
 [6.]
 [6.]
 [1.]
 [0.]
 [3.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [5.]
 [4.]
 [4.]
 [0.]
 [0.]
 [0.]
 [5.]
 [0.]
 [0.]
 [1.]
 [3.]
 [0.]
 [0.]
 [1.]
 [3.]
 [5.]
 [5.]
 [1.]
 [5.]
 [1.]
 [0.]
 [0.]
 [6.]
 [0.]
 [0.]
 [0.]
 [0.]
 [5.]
 [4.]
 [6.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [3.]
 [3.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [6.]
 [3.]
 [0.]
 [0.]
 [2.]
 [6.]
 [1.]
 [1.]
 [2.]
 [6.]
 [3.]
 [1.]
 [0.]
 [6.]
 [3.]
 [1.]
 [5.]
 [4.]
 [2.]
 [2.]
 [3.]
 [0.]
 [0.]
 [1.]
 [0.]
 [5.]
 [0.]
 [6.]
 [1.]]


In [20]:
nb_class = 7   # 0 ~ 6 => Y
X = tf.placeholder(tf.float32, [None, 16])
Y = tf.placeholder(tf.int32, [None, 1])

Y_one_hot = tf.one_hot(Y, nb_class)
print("one_hot", Y_one_hot)

Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_class])
print("reshape", Y_one_hot)

W = tf.Variable(tf.random_normal([16, nb_class]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_class]), name = 'bias')


logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

cost_i = tf.nn.softmax_cross_entropy_with_logits(logits = logits,
                                                 labels = Y_one_hot)
cost = tf.reduce_mean(cost_i)
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

one_hot Tensor("one_hot_2:0", shape=(?, 1, 7), dtype=float32)
reshape Tensor("Reshape_1:0", shape=(?, 7), dtype=float32)
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.



In [22]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2000+1)):
    sess.run(optimizer, feed_dict = { X : x_data, Y : y_data})
    if step % 100 == 0:
        loss, acc = sess.run([cost, accuracy], feed_dict = { X : x_data, Y : y_data})
        print("Step : {:5}, \t Loss : {:.3f}, \t Acc : {:.2%}".format(step, loss, acc))    
    

Step :     0, 	 Loss : 8.084, 	 Acc : 8.91%
Step :   100, 	 Loss : 0.604, 	 Acc : 78.22%
Step :   200, 	 Loss : 0.363, 	 Acc : 92.08%
Step :   300, 	 Loss : 0.269, 	 Acc : 96.04%
Step :   400, 	 Loss : 0.214, 	 Acc : 96.04%
Step :   500, 	 Loss : 0.177, 	 Acc : 97.03%
Step :   600, 	 Loss : 0.150, 	 Acc : 97.03%
Step :   700, 	 Loss : 0.131, 	 Acc : 98.02%
Step :   800, 	 Loss : 0.116, 	 Acc : 98.02%
Step :   900, 	 Loss : 0.104, 	 Acc : 100.00%
Step :  1000, 	 Loss : 0.094, 	 Acc : 100.00%
Step :  1100, 	 Loss : 0.086, 	 Acc : 100.00%
Step :  1200, 	 Loss : 0.080, 	 Acc : 100.00%
Step :  1300, 	 Loss : 0.074, 	 Acc : 100.00%
Step :  1400, 	 Loss : 0.069, 	 Acc : 100.00%
Step :  1500, 	 Loss : 0.065, 	 Acc : 100.00%
Step :  1600, 	 Loss : 0.061, 	 Acc : 100.00%
Step :  1700, 	 Loss : 0.058, 	 Acc : 100.00%
Step :  1800, 	 Loss : 0.055, 	 Acc : 100.00%
Step :  1900, 	 Loss : 0.052, 	 Acc : 100.00%
Step :  2000, 	 Loss : 0.050, 	 Acc : 100.00%



In [23]:
pred = sess.run(prediction, feed_dict = { X : x_data})
for p, y in zip(pred, y_data.flatten()):
    print("[{}] Prediction : {}, True Y : {}".format(p == int(y), p, int(y)))

[True] Prediction : 0, True Y : 0
[True] Prediction : 0, True Y : 0
[True] Prediction : 3, True Y : 3
[True] Prediction : 0, True Y : 0
[True] Prediction : 0, True Y : 0
[True] Prediction : 0, True Y : 0
[True] Prediction : 0, True Y : 0
[True] Prediction : 3, True Y : 3
[True] Prediction : 3, True Y : 3
[True] Prediction : 0, True Y : 0
[True] Prediction : 0, True Y : 0
[True] Prediction : 1, True Y : 1
[True] Prediction : 3, True Y : 3
[True] Prediction : 6, True Y : 6
[True] Prediction : 6, True Y : 6
[True] Prediction : 6, True Y : 6
[True] Prediction : 1, True Y : 1
[True] Prediction : 0, True Y : 0
[True] Prediction : 3, True Y : 3
[True] Prediction : 0, True Y : 0
[True] Prediction : 1, True Y : 1
[True] Prediction : 1, True Y : 1
[True] Prediction : 0, True Y : 0
[True] Prediction : 1, True Y : 1
[True] Prediction : 5, True Y : 5
[True] Prediction : 4, True Y : 4
[True] Prediction : 4, True Y : 4
[True] Prediction : 0, True Y : 0
[True] Prediction : 0, True Y : 0
[True] Predict